### ISSUE TITLE
Columns in drag and drop quizzes are swapped

### ISSUE THREAD

**Issue by alfredsasko** [udacimak/udacimak#107]
**Describe the bug**
Each drag and drop quizzes have 2 columns where they values are swapped, means column 1 contains values of column 2 and vise versa. See attached screen shot. Left side is rendered right side is original.

**To Reproduce**
1. Install nvm-windows
2. Install udacimak v1.4.5 (to have video quality 720pxls)
3. Download and render nd025 (dsnd)

**Expected behavior**
Rendered successfully, need to check content (see screen-shot)

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Node version: v13.12.0
 - npm version: 6.4.14
 - Udacimak Version: v1.4.5.
 - Browser:  Chrome

**Course Information**
 - Nanodegree or Course name: [Data Scientist Nanodegree]
 - Version: ...
 - Locale: en-us

**Additional context**
![drag_drop_quizze_swap](https://user-images.githubusercontent.com/44699562/78454335-bfe7cc00-7697-11ea-8be2-57449e4e602f.png)
![drag_drop_quizze_swap](https://user-images.githubusercontent.com/44699562/78454133-6b901c80-7696-11ea-9e93-123e9d1e27ef.png)

**Comment by udacimak** [comment]
Could you please send me all the `data.json` files to udacimak@tutanota.com so I can have a look?
