### ISSUE TITLE
Quizzes question does not render unknown quizzes type.

### ISSUE THREAD

**Issue by alfredsasko** [udacimak/udacimak#109]
**Describe the bug**
After rendering some of the quizzes questions has not been rendered showing unknown quizzes type description. See screen-shot.

**To Reproduce**
1. Install nvm-windows
2. Install udacimak v1.4.5 (to have video quality 720pxls)
3. Download and render nd025 (dsnd)

**Expected behavior**
Rendered successfully, need to check content (see screen-shot)

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Node version: v13.12.0
 - npm version: 6.4.14
 - Udacimak Version: v1.4.5.
 - Browser:  Chrome

**Course Information**
 - Nanodegree or Course name: [Data Scientist Nanodegree]
 - Version: ...
 - Locale: en-us
![uknown_quize_type](https://user-images.githubusercontent.com/44699562/78454652-bc554480-7699-11ea-9a27-3ac95e80c003.png)

**Additional context**

**Comment by udacimak** [comment]
Could you please send me all the `data.json` files to udacimak@tutanota.com?
Please also let me know exactly where to find this quiz (You can give me the `url` that shows up when you open this page)

**Comment by udacimak** [comment]
> Could you please send me all the data.json files to udacimak@protonmail.com?
Please also let me know exactly where to find this quiz (You can give me the url that shows up when you open this page)

I'm closing this issue since I can't support a new quiz type without knowing its data structure
