### ISSUE TITLE
Error when trying to install using npm

### ISSUE THREAD

**Issue by gamingneeds** [udacimak/udacimak#11]
I'm receiving this error:

PS C:\> npm install -g udacimak
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/przemyslawpluta/node-youtube-dl.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by udacimak** [comment]
I think you need to install `git` on your machine.

Please try and let me know if it works. I will update the `README` for a future release regarding `git` requirement.
