### ISSUE TITLE
Update youtube-dl depencency to 3.0.2

### ISSUE THREAD

**Issue by miguelusque** [udacimak/udacimak#110]
Hi,

It might be useful to update youtube-dl dependency to 3.0.2

It might solve some errors found while downloading videos at higher resolutions

Hope it helps!
Miguel

**Comment by abenacamp** [comment]
Please can you help me to download, beacause i am getting an error message error code 5000

**Comment by udacimak** [comment]
Updated in 9835e7216eed268c24eab2b082076050c915c1ca

**Comment by miguelusque** [comment]
Thank you!!!!!!
