### ISSUE TITLE
subtitles not download through Udacity ND

### ISSUE THREAD

**Issue by wael-abdin** [udacimak/udacimak#116]
I used the following command to render the Front End nanodegree course after download it :

```
udacimak render /home/Front\ End\ Developer\ v1.0.0/ --verbose --userquizanswer --subtitles --targetdir /home/Render_Front_End_Developer_v1.0.0/
```

It downloaded the course but without any subtitles !
What is the problem ?
![Screenshot from 2020-04-09 17-00-05](https://user-images.githubusercontent.com/34836253/78909987-8f7fa380-7a84-11ea-8c0e-cbb4063ee201.png)

**Comment by udacimak** [comment]
After you run the `render` command with `--subtitles` parameter, when the CLI downloads Youtube videos, do you see it says it's downloading subtitles like below?

```
√ Getting Youtube video id fxNSn63xFvA information
 ████████████████████████████████████████ 100% | ETA: 1s | 1129344/1129344
2020-04-10T00:40:42.823Z [info]: Downloaded video 02. Introduction-fxNSn63xFvA.mp4
| Download subtitles for 02. Introduction-fxNSn63xFvA 
```

**Comment by wael-abdin** [comment]
yes, It says Download Subtitles for each video, but no thing actually downloaded

**Comment by udacimak** [comment]
I suspect that there are no subtitles for those videos maybe? Could you send all the `data.json` files to udacimak@protonmail.com so I can test on my computer?

**Comment by wael-abdin** [comment]
first of all, thank you very much for your kindly support and fast respons.
regarding to your last reply :
the video course have a subtitles.
the following is explaination why i am sure that it have a subtitles:

i was intend to dowload two nano degree courses.
i already download the first course, but i noted that half of the course downloaded with subtitles perfectly and the other half without subtitles.
So, i repeated download the course again from the begaining from the same data.json files but i noted that i download without the subtitles completely even the first half which downloaded before with subtitles, it downloaded without it.
i repeated this operation many times but the same result.
i sent to you the data.json files on email

thank you in advance.

**Comment by udacimak** [comment]
I tried to `render` but the subtitles are also not downloaded.

I tried to directly use [`youtube-dl`](https://youtube-dl.org/) to download the video with subtitles, but it's also not successful:

```
(venv) λ youtube-dl TOmVNaQZgMU --verbose --all-subs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['TOmVNaQZgMU', '--verbose', '--all-subs']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] TOmVNaQZgMU: Downloading webpage
WARNING: unable to download video subtitles: Unable to download XML: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r1---sn-uxanug5-hxaee.googlevideo.com/videoplayback?expire=1586623148&ei=TJ6RXu6ELZj34-EPoMaTyAE&ip=2001%3A8003%3A444f%3A4100%3Ad6b%3A2964%3Ae89c%3Ad1c1&id=o-ANuCzSYtnYv1ToPG9-v7XLOyu6Tmx_bdvlonHVb8-N9l&itag=22&source=youtube&requiressl=yes&mh=Z1&mm=31%2C29&mn=sn-uxanug5-hxaee%2Csn-ntqe6n7k&ms=au%2Crdu&mv=m&mvi=0&pl=39&initcwndbps=1246250&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=30.093&lmt=1565295268113775&mt=1586601455&fvip=4&c=WEB&txp=2316222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AJpPlLswRQIgNwQf-owzR7wQXSTLe1RCaoFvvqUmVyOmzc1MQXrrxowCIQD9nrkRkPMApWvyQqESgKR5QTEUE8cVbC8-9VvVbyc7bg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgCffgtTmQQhRdbWJsmRYCmQWAnwWCuBi1XHf9FSNOdJMCIQC3ZLzYlQKX8hlRmwEEAMpfb9sKnrBHN7bmDMYFkZj7hw%3D%3D'
[download] Destination: ND001 C01 L05 01 Building Layouts With Grid-TOmVNaQZgMU.mp4
[download] 100% of 1.91MiB in 00:00
```

So for some reason the subtitles are not available for download - even though when I watch the video on Youtube, it does have subtitles.

I can't resolve this issue but you can open an issue on `youtube-dl`'s Github pages if desired
