### ISSUE TITLE
when u try to set token getting error previously its working fine 3 days ego but today getting error

### ISSUE THREAD

**Issue by jagadeeshsandireddy** [udacimak/udacimak#119]
![Screenshot (341)](https://user-images.githubusercontent.com/33963028/79041395-2d05df00-7c0d-11ea-8ca8-33a04bcc4d24.png)
Getting this error when u try to set token

**Comment by udacimak** [comment]
Could you try uninstalling and re-install Udacimak?

**Comment by jagadeeshsandireddy** [comment]
uninstalling and re-install worked thank you
