### ISSUE TITLE
where can I find the subtitle file

### ISSUE THREAD

**Issue by imfool456** [udacimak/udacimak#120]
I use -s option. I can download everything correctly. I saw subtitles has been downloaded. But I didn't see this file. When play, I didn't see the option I can turn on cc. Also I setup web server, I didn't see subtitle either. Did I miss anything? Thanks!

---
✔ Getting Youtube video id ZE_U_036EBA information
 ████████████████████████████████████████ 100% | ETA: 0s | 6401324/6401324
2020-04-12T00:35:50.165Z [info]: Downloaded video 06. C3 L2 L4 Control Diagrams V1-ZE_U_036EBA.mp4
**✔ Download subtitles for 06. C3 L2 L4 Control Diagrams V1-ZE_U_036EBA**
✔ Download media file 04-simple-control-diagrams-5-v2.png

**Comment by udacimak** [comment]
Could you please send all the JSON files to udacimak@protonmail.com? I can have a look

**Comment by udacimak** [comment]
So I've checked and I've seen this issue before.

For some reason, `youtube-dl` can't download subtitles for some videos. So, unfortunately, Udacimak can't solve this issue on its own

**Comment by imfool456** [comment]
thanks! I'll manually download the subtitle if need.

**Comment by abenacamp** [comment]
when the subtitle is downloaded to see it on the videos or use it use chrome web server to open to the folder and when it is playing the subtitles will show thanks

**Comment by miguelangel** [comment]
Hi!

Could you please have a look at this issue again? I had previously downloaded a nanodegree with a previous version of udacimak (a couple of weeks ago), and now I cannot download the subtitles anymore.

Thanks!
Miguel

**Comment by abenacamp** [comment]
add the option -st when rendering

**Comment by imfool456** [comment]
@abenacamp 
do you mean we need to use -st option rather than 0-s? 

-s, --subtitles               (Optional) Download Youtube video subtitles

**Comment by abenacamp** [comment]
yeah

**Comment by miguelusque** [comment]
Hi @abenacamp  ,

It doesn't work either.

Hi @udacimak ,

Could you please have a look at this issue? A couple of weeks ago, I was able to download the video subtitles with udacimak. With the latest version of udacimak, I cannot.

I have double checked I can download the subtitles with youtube-dl from command line:

youtube-dl https://www.youtube.com/watch\?v\=werDy_UpcMY --write-auto-sub

Thank you both!

Regards,
Miguel
