### ISSUE TITLE
Unexpected Token error(Parsing error)

### ISSUE THREAD

**Issue by Syed-Hazim** [udacimak/udacimak#121]
Any commands with udacity-dl produce the following output

![image](https://user-images.githubusercontent.com/63338631/79065885-45d7c880-7cd1-11ea-9745-a1c0341fc2a4.png)

 - OS: Linux Mint
 - Node version: (`v8.10.0`)
 - npm version: (3.5.2)
 - Udacimak Version: (`udacimak --version`)On running this command the output is the attached screenshot
 - Browser [Firefox]

**Course Information**
 - Nanodegree or Course name: Introduction to Computer Vision v1.0.0

 - Locale: [ en-us]

**Comment by 3lv27** [comment]
You need to update your node version, I recommend you to use v.12.16.2 which is currently the LTS.  Let me know if that works.

**Comment by Syed-Hazim** [comment]
That worked! Thanks a ton! Do Appreciate this : )
