### ISSUE TITLE
subtitles are downloaded but not playing

### ISSUE THREAD

**Issue by jagadeeshsandireddy** [udacimak/udacimak#124]
used below command to download subtitles they are downloaded but not displaying in video
udacimak render "Data Scientist Nanodegree v3.0.0" --targetdir "Data Scientist Nanodegree v3.0.0 Output" --subtitles

**Comment by udacimak** [comment]
Please check this:

- https://github.com/udacimak/udacimak/wiki/How-to-Use#watching-video-with-subtitles

**Comment by jagadeeshsandireddy** [comment]
Okay Thank you
