### ISSUE TITLE
Failed to download youtube video! ISSUE FIXED!

### ISSUE THREAD

**Issue by kaflenitish** [udacimak/udacimak#127]
Everyone around here have been dealing with the issue regarding youtube-dl and how they were not being able to solve the issue.
My head hurt when trying to fix it, tried in multiple devices, then finally worked!

If you are dealing that issue on a MacOS, then you need root access and follow the process!

The bug seems to be problematic for Windows here.

FIX: 
![Annotation 2020-04-24 234143](https://user-images.githubusercontent.com/47726833/80270363-2f445080-8685-11ea-8aa8-4356880cea6a.png)

When you go to the website: `https://ytdl-org.github.io/youtube-dl/download.html` to get your youtube-dl file, you will notice the requirment for "Microsoft Visual C++ 2010 Redistributable Package (x86)". 
While your system does have multiple redistributable package, click on that or download it from `https://www.microsoft.com/en-US/download/details.aspx?id=5555`

After you have installed it, you can open the bash, and try rendering and the problem with youtube will dissapear and your download will work!

![Annotation 2020-04-24 234333](https://user-images.githubusercontent.com/47726833/80270386-72062880-8685-11ea-8cf5-2e1bb0d07af1.png)

**Comment by udacimak** [comment]
Thanks. Please post this as a reply to the relevant issue if you can.

I've also included your instructions here:
- https://github.com/udacimak/udacimak/wiki/Install-&-Update#installation
