### ISSUE TITLE
Nanodegree/course JSON repo

### ISSUE THREAD

**Issue by nerddan** [udacimak/udacimak#131]
I made a repo so people can share their JSON files.
https://github.com/nerddan/udacimak-repos

Feel free if you would like to fork or build your own version. I just want a place to share.

I understand this should not be an issue, and I wish you could open the discussion zone.

Cheers!

**Comment by PyFinn** [comment]
really appreciate this

**Comment by doublemint12** [comment]
Very very cool. 

You think it's likely that we can submit workspace files as well? Like maybe the practice solutions so we catch the important points. Or even just project datasets so we can give it a shot? 

I understand that it's a bit of manual work but figured if we start early people will follow the trend, hopefully. 

Thanks for doing this!

**Comment by nerddan** [comment]
@PyFinn @doublemint12 Can you guys upload your nanodegrees/courses?

**Comment by victorawogbemi** [comment]
@nerddan I think you should make a quick tutorial on how to make pull requests and add to your repo for newer people on github.

**Comment by PyFinn** [comment]
> @PyFinn @doublemint12 Can you guys share your nanodegrees/courses by PR?

I´ll share my Nanodegrees!

**Comment by victorawogbemi** [comment]
@PyFinn @doublemint12 So pretty much fork nerddan's udacimak repo 
![image](https://user-images.githubusercontent.com/21068868/80644951-79885180-8a38-11ea-9230-a856a8a6f8a1.png)
Then in your fork go into to the meta folder
![image](https://user-images.githubusercontent.com/21068868/80645046-9755b680-8a38-11ea-9fa5-22064b954f4c.png)
Click upload files and upload your course folder
![image](https://user-images.githubusercontent.com/21068868/80645147-b9e7cf80-8a38-11ea-94c1-b7e6c50eb110.png)
Add a name for the commit (i.e course you are uploading ) and press commit
![image](https://user-images.githubusercontent.com/21068868/80645360-fca9a780-8a38-11ea-99e7-5154dfa31c41.png)
Then go to your repo page and it should say your branch is ahead, create pull request
![image](https://user-images.githubusercontent.com/21068868/80645502-37abdb00-8a39-11ea-92a2-87f698e114eb.png)
Then like click the green button and you should be done

**Comment by nerddan** [comment]
@victorawogbemi 
Thank you for making this! I also wrote a brief tutorial in `README.md`. Maybe you want to merge my latest changes.
Also, I updated `download.sh` so users can choose the course for downloading.

**Comment by udacimak** [comment]
@nerddan Udacity's content is proprietary. I built Udacimak so that people can use the course offline for personal use only and I don't think publicly sharing their data is legal.
