### ISSUE TITLE
Can't render JSoN file

### ISSUE THREAD

**Issue by alaa-emad** [udacimak/udacimak#132]
i couldn't render th JSON files , i always got the folder not exist or no data in JSON file

**Comment by PyFinn** [comment]
Whats your operating system?

**Comment by alaa-emad** [comment]
> Whats your operating system?

i tried it on linux and windows 10 also my friend tried it and the same issue

**Comment by udacimak** [comment]
Please use the template when submitting the issue to clearly explain why the `render` fails
