### ISSUE TITLE
STACK: Error: connect EHOSTUNREACH 

### ISSUE THREAD

**Issue by doublemint12** [udacimak/udacimak#133]
**STACK: Error: connect EHOSTUNREACH**

Hi There!

Just wanted to ask a quick question in regards to the issue I'm having when I'm trying to render my UX Design Nanodegree coursework. 

I did a quick search for EHOSTUNREACH on Udacimak's issues page but I couldn't find anything. It seems like an API issue b/c it's giving me some IP address that's not mine. I do have Windscribe VPN downloaded but wasn't using it on my Mac (Catalina). 
 
If there is no solution for this then, is there a way for Udacimak to continue rendering and skip whatever it can't render? My terminal shell output is shown below.

```shell
 Getting Youtube video id Dd7KuTSCXm8 information
 ████████████████████████████████████████ 100% | ETA: 0s | 6073623/6073623
2020-04-27T21:18:27.857Z [info]: Downloaded video 06. ND578 C03 L02 06 High-Fidelity Design With Figma - Plugins-Dd7KuTSCXm8.mp4
2020-04-27T21:18:27.880Z [info]: Completed rendering lesson file /Users/Preston/Desktop/UXDESIGN/Part 04-Module 01-Lesson 03_Building Interactive Designs/06. Figma - Plugins.html
2020-04-27T21:18:27.880Z [info]: ____________________

✔ Download media file screen-shot-2020-01-16-at-11.02.01-am.png
2020-04-27T21:18:27.915Z [info]: Downloaded media file screen-shot-2020-01-16-at-11.02.01-am.png
✔ Getting Youtube video id pdy9eEVYWLk information
 ████████████████████████████████████████ 100% | ETA: 1s | 9015769/9015769
2020-04-27T21:18:31.739Z [info]: Downloaded video 07. ND578 C03 L02 12 Solution- Plugins-pdy9eEVYWLk.mp4
✖ Download media file 969249.gif
2020-04-27T21:18:31.746Z [error]: ERROR: connect EHOSTUNREACH 0.0.0.73:443 - Local (192.168.86.54:57093)
CODE: EHOSTUNREACH
STACK: Error: connect EHOSTUNREACH 0.0.0.73:443 - Local (192.168.86.54:57093)
    at internalConnect (net.js:921:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:296:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1063:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:10)
Preston@macbook-pro Desktop % 

```

**Desktop :**
 - OS: [macOS Catalina]
 - Node version: (`v12.16.2`)
 - npm version: (`6.14.4`)
 - Udacimak Version: (`v1.6.2`)
 - Browser [safari]

**Course Information**
 - UX Designer Nano-degree 
 - Version: 1.0.0 
 - Locale: en-us

**Additional context**
Lastly, will Udacimak continue to support older nano-degrees versions? It looks like it's getting updated pretty frequently and I was wondering if older Udacimak versions get deprecated as well. 

It looks like it's gonna be a large size when it gets fully rendered so I saved the original Json data I downloaded from running "udacimak download nd578". 

I was hoping I can render my nanodegree version (v1.0.0) when I no longer have the access to my account. 

Also, thank you so much for putting this out for us!
It's super interesting to learn how it works. 

Thank you very much for your time.

**Comment by udacimak** [comment]
Could you please send the JSON data to udacimak@protonmail.com ? I suspect that the image file being downloaded might be unavailable.

Or you can also check yourself by reading the JSON data - check for the URL of the media file that's causing the issue.

> Lastly, will Udacimak continue to support older nano-degrees versions? It looks like it's getting updated pretty frequently and I was wondering if older Udacimak versions get deprecated as well.

Udacimak can render whichever Nanodegree version of the JSON data files that you have - so it's a good idea that you're keeping the JSON data to download later 👍

**Comment by doublemint12** [comment]
Thank you so much!

**Comment by udacimak** [comment]
You're welcomed! I'm opening this issue again because I'm debugging and updating Udacimak.
