### ISSUE TITLE
udacity : jupyter workspace download automatically

### ISSUE THREAD

**Issue by surajy93** [udacimak/udacimak#134]
i have found workspace link but when i visit it need access, so it is possible to give access automatically and download this workspace.
if possible then we can render just by change the workspace id we can download all jupyter workspace automatically.

udacity workspace link : https://view3854ccca.udacity-student-workspaces.com/tree?
 **### "workspace_id": "viewuah6hrp8uld",**
 "atoms": [
            {
              "id": 751926,
              "key": "efbb5008-d830-4734-a748-2cbd49909d30",
              "title": null,
              "semantic_type": "WorkspaceAtom",
              "is_public": true,
              **### "workspace_id": "viewuah6hrp8uld",**
              "pool_id": "jupytergpu",
              "view_id": "jupyter-2632dc8d709",
              "gpu_capable": true,
              "configuration": {
                "id": "reserved",
                "blueprint": {
                  "conf": {
                    "disk": null,
                    "ports": [],
                    "allowGrade": false,
                    "allowSubmit": false,
                    "defaultPath": "/notebooks/Sentiment_RNN_Exercise.ipynb"
                  },
                  "kind": "jupyter"
                },
                "workspaceId": "reserved"
              },
              "starter_files": null
            }
          ]

**Comment by udacimak** [comment]
I've had a look at this before - but couldn't find a way to download all workspace files with the CLI. I don't think it's possible. In addition, many workspace files are huge in Gibabytes (ie. in AI/data courses). So this feature can't be implemented, unfortunately.

**Comment by surajy93** [comment]
without workspace i found course downloading is useless.
thanks for such a effort.
