### ISSUE TITLE
Unhandled Promise Rejection Error

### ISSUE THREAD

**Issue by lightc786** [udacimak/udacimak#136]
Downloading User Experience Nanodegree, I encounter this error. I've downloaded over 10 courses and have not encountered this error before. I looked for "969249" in each of the JSON files but did not find a match. I was seeing if I could modify the JSON to just skip over this file and continue the course download but haven't had any luck.

```
✖ Download media file 969249.gif
2020-04-29T22:39:18.637Z [error]: Unhandled Promise Rejection:
ERROR: connect EINVAL 0.0.0.73:443 - Local (0.0.0.0:0)
CODE: EINVAL
STACK: Error: connect EINVAL 0.0.0.73:443 - Local (0.0.0.0:0)
    at internalConnect (net.js:888:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1035:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:63:10)
```

**Course Information**
User Experience Nanodegree v1.0.0 - Version: [e.g. v1.0.0]

**Comment by udacimak** [comment]
There's an issue with the UX Nanodegree that the JSON with id `969249` contains invalid URL.

You can use Visual Studio Code, press Ctrl + Shift + F to search all JSON files for `969249`, then use the value in `non_google_url` key and copy that URL value to `url` key to temporary fix the issue.

I'll need to make an update in the next release for Udacimak to handle such a case when the URL is not valid.

**Comment by lightc786** [comment]
For some reason, I cannot seem to find the reference of 969249 using Visual Studio Code. Not sure where it is referencing 969249 or 969249.gif.

**Comment by udacimak** [comment]
Please update Udacimak, the issue has been handled
