### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/bin/details

### ISSUE THREAD

**Issue by cipheraxat** [udacimak/udacimak#144]
Hey @udacimak how can I get through this?

(base) akshat@akshat-Inspiron-5570:~$ sudo udacimak login
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/bin/details'
    at Object.openSync (fs.js:443:3)
    at readFileSync (fs.js:343:35)
    at module.exports (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/get-binary.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:18:41)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

**Comment by INNFINITEMINDS** [comment]
> Hey @udacimak how can I get through this?
> 
> (base) akshat@akshat-Inspiron-5570:~$ sudo udacimak login
> fs.js:114
> throw err;
> ^
> 
> Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/bin/details'
> at Object.openSync (fs.js:443:3)
> at readFileSync (fs.js:343:35)
> at module.exports (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/get-binary.js:15:30)
> at Object. (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:18:41)
> at Module._compile (internal/modules/cjs/loader.js:778:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> at Module.load (internal/modules/cjs/loader.js:653:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> at Module.require (internal/modules/cjs/loader.js:692:17)

have u got any solution ?

**Comment by cipheraxat** [comment]
@INNFINITEMINDS nope .

**Comment by udacimak** [comment]
I'm not sure what's causing the issue yet cause I can't replicate this. Do you have access to try on a Ubuntu computer or a Docker image?

**Comment by cipheraxat** [comment]
@udacimak it worked well on windows but didn't get why it's not working on my ubuntu OS know.

**Comment by INNFINITEMINDS** [comment]
> I'm not sure what's causing the issue yet cause I can't replicate this. Do you have access to try on a Ubuntu computer or a Docker image?

working properly using docker.:)
but unable to run on windows
