### ISSUE TITLE
Next button

### ISSUE THREAD

**Issue by jrao1** [udacimak/udacimak#15]
Sorry, not sure if I'm using this correctly but after I rendered a course (cs373), and start the index.html to look at each lesson, I can choose which part of the lesson by using the left panel which lists 01, 02, etc. But once I'm in a part, there's no "Next" button to go to the next section of the lesson?

<img width="941" alt="udacimak" src="https://user-images.githubusercontent.com/1448278/50965699-b19b1680-150d-11e9-8b2a-de0b3aed732e.PNG">

 The Udacity website seems to have this button:

<img width="937" alt="udacity" src="https://user-images.githubusercontent.com/1448278/50965708-b8c22480-150d-11e9-9805-e99d7a838fd5.PNG">

**Comment by udacimak** [comment]
@jrao1 I didn't design the __Next__ button, so the only option is to find the next lesson from the side menu to go to that lesson.

**Comment by udacimak** [comment]
@jrao1 
I haven't got time to work on this yet but will consider for the next release

**Comment by jrao1** [comment]
I took a shot at implementing this, here's the patch. I also added the feature to auto scroll to first video, auto play video, and auto scroll for the sidebar.

[patch.txt](https://github.com/udacimak/udacimak/files/2776611/patch.txt)

**Comment by udacimak** [comment]
Thanks, @jrao1 

Could you please submit a pull request? I'm not able to check from the git diff content.

**Comment by jrao1** [comment]
Ok, pull request submitted.

**Comment by udacimak** [comment]
Thanks, @jrao1 !
I'm quiet busy at the moment but will have a look as soon as I can.
