### ISSUE TITLE
Unable to download youtube videos

### ISSUE THREAD

**Issue by hc2acc** [udacimak/udacimak#158]
I was downloading a few nanodegrees, all of it was working perfectly fine, till the morning today.
Today, when I tried resuming my download, none of the videos get downloaded and keep reporting an error
```
× Getting Youtube video (id=kNxZwfXwvuk) information with quality="22"
2020-06-18T05:26:19.570Z [error]: Failed to download youtube video with id kNxZwfXwvuk with quality="22", retrying with quality="18"
× Getting Youtube video (id=kNxZwfXwvuk) information with quality="18"
2020-06-18T05:26:23.800Z [error]: Failed to download youtube video with id kNxZwfXwvuk with quality="18", retrying with quality=""
× Getting Youtube video (id=kNxZwfXwvuk) information with quality=""
2020-06-18T05:26:28.303Z [error]: Youtube video with id kNxZwfXwvuk could not be downloaded available. The CLI will ignore this error and skip this download. Please check this error message:

"Command failed with exit code 1: C:\\Users\\hot9c\\AppData\\Roaming\\npm\\node_modules\\udacimak\\node_modules\\youtube-dl\\bin\\youtube-dl.exe --dump-json -f best --verbose --encoding utf8 http://www.youtube.com/watch?v=kNxZwfXwvuk"
```
This is when I'm downloading the data analytics nanodegree.

I don't quite understand it because I've been downloading a few nanodegrees for a couple of weeks now and every nanodegree donwload has gone fine. I have a problem all of a sudden, completely out of the blue.

My udacimak version is 1.6.6, ie updated to the latest. 
Windows 10 OS. 

![image](https://user-images.githubusercontent.com/67089650/84983459-78c98d00-b156-11ea-92ae-f025f26893fd.png)

But really, if this was an issue with a version or something, then I would expect my previous download which was only yesterday to have failed too. But that worked. So what happened overnight?

EDIT: I decided to go back and try to redownload my old nanodegrees(I had their json files saved).
So, the videos now don't download for those nanodegrees either. That is, the downloads fail even for nanodegrees which were being downloaded successfully in the past(as recently as 1 week ago).
I only have a few days of my free nanodegree course left unfortunately, I request you to look into it as soon as possible.

**Comment by update-udaci** [comment]
Hi I just downloaded Data analyst nanodegree program using data.jason file and everything seems to be fine.Maybe u should reinstalling  udacimak.
![github query](https://user-images.githubusercontent.com/66868955/85044741-b1478600-b1ab-11ea-994c-4e6dca54fc06.jpg)
 udacimak version 1.6.6

**Comment by hc2acc** [comment]
Okay, the problem was with my expiring license key for my OS, apparently. Reinstalling udacimak and other solutions didn't solve it, but reactivating my OS key did. For anyone else who faces the issue, this might be your problem.
