### ISSUE TITLE
error while downloading the youtube videos 

### ISSUE THREAD

**Issue by sasidhar-programmer** [udacimak/udacimak#162]
**Describe the bug**

Command failed with exit code 1: C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\udacimak\\node_modules\\youtube-dl\\bin\\youtube-dl.exe --dump-json -f best --encoding utf8 http://www.youtube.com/watch?v=w2lV5_S2_2A"

**To Reproduce**
5. _(Add more or edit as appropriate)_

**Expected behavior**

**Udacimak Log**
Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:

**Desktop (please complete the following information):**
 - OS:  windows 
 - Node version: 14.4.0
 - npm version: 6.14.5
 - Udacimak Version: 1.6.6
 - Browser : chrome 

**Course Information**
 - Nanodegree or Course name: [Flying car nanodegree]
 - Version: 2.0.0
 - Locale: [e.g. en-us]

**Additional context**

**Comment by sainyinyimoe** [comment]
I faced the same issue. I uninstall node.js and restart my computer and reinstall node.js again.
Render again.
It work well.

**Comment by sasidhar-programmer** [comment]
@sainyinyimoe   Thank you . It worked
