### ISSUE TITLE
404 error display

### ISSUE THREAD

**Issue by ebuka-odih** [udacimak/udacimak#174]
First, i want to thank the team behind this awesome project.

after installing Udacimak, I ran npx serve as instructed, I opened the port on my browser and the home page displayed, when I navigate into the course and tried to play the videos i get "404 the requested path could not be found"

**Comment by ebuka-odih** [comment]
i fixed it already. thank you.

**Comment by ghost** [comment]
Hi, I am facing the same issue. Could you please share how you fixed it?

**Comment by ghost** [comment]
@ebuka-odih
