### ISSUE TITLE
`Supporting Materials` Links not updated on the rendered files

### ISSUE THREAD

**Issue by heysachin** [udacimak/udacimak#21]
**Describe the bug**
None of the extra materials (Supporting Materials) links provided by Udacity on the bottom of the course pages are not updated on the rendered pages.

**To Reproduce**
1. Go to the Nanodegree
2. Click on Any Module and any page
3. Scroll down to the bottom
4. The Supporting Material links as found on the nanodegree page are not found.
5. _(Add more or edit as appropriate)_

**Expected behavior**

Download links 
<img width="1102" alt="screenshot 2019-01-26 at 12 31 20 am" src="https://user-images.githubusercontent.com/20176458/51767140-78b09380-2102-11e9-9c27-acb1dabb4437.png">

**Udacimak Log**
Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:

```shell
INSERT_LOG_HERE
```

**Screenshots**

**Desktop (please complete the following information):**
 - Node version: (`node --version`)
 - npm version: (`npm --version`)
 - Udacimak Version: (`udacimak --version`)

**Course Information**
 - Nanodegree or Course name: [e.g. Front End Web Developer Nanodegree]
 - Version: [e.g. v1.0.0]
 - Locale: [e.g. en-us]

**Additional context**

**Comment by udacimak** [comment]
Hi @heysachin,

Could you please send me the `data.json` file to udacimak@tutanota.com ?

**Comment by udacimak** [comment]
@heysachin 
Looks like I overlooked the resource files in JSON data when developing, so I'll need to add a new feature to download them.
I'll consider this and have a go when I have time and will release this with the next version.

**Comment by udacimak** [comment]
@heysachin I was looking at this feature and decided not to implement it. 
Supporting materials can be downloaded when using the rendered version of the Nanodegree/course.
I opt not to download it locally while rendering since the resource is not embedded in a JSON key, but rather in the Markdown text of the lesson content, which can be very confusing for the renderer to parse and download.
