### ISSUE TITLE
Rendering ERROR: socket hang up

### ISSUE THREAD

**Issue by navidsafaeian** [udacimak/udacimak#23]
I got  "ERROR: socket hang up" while rendering the Json file. I've tried rendering from scratch several times, but still received the same error, each time at a different video. You can see the error sample as follows:

✖ Getting Youtube video id 1bq6c44nQnU information
2019-02-27T18:49:41.287Z [error]: ERROR: socket hang up
CODE: ECONNRESET
STACK: Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:431:23)
    at TLSSocket.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

My OS is Linux (Ubuntu 16.04) and I am trying to download my materials, every time rendering stops at downloading a different video as above!!

**Comment by udacimak** [comment]
Hi @navidsafaeian 

This is a network issue and I'm not able to debug. 
Have you tried on a different network to see if the CLI can run?

**Comment by navidsafaeian** [comment]
Thank you. Finally I coud render all courses after about 20 times errors
and stops.
Many thanks for the downloader package by which I can easily have all my
nanodegree for ever without any missing courses and lecture video.
Regards
Navid
