### ISSUE TITLE
Certificate has expired 

### ISSUE THREAD

**Issue by jaideepheer** [udacimak/udacimak#24]
**Describe the bug**
During rendering, I get a certificate expired error for [this](https://www.youtube.com/watch?v=HrYNL_1SV2Y) youtube video.
If I change the `data.json` for this lesson to exclude this `VideoAtom` object then it works fine. It can 
 download all other videos.

**Udacimak Log**
> × Getting Youtube video id HrYNL_1SV2Y information
2019-03-01T15:44:14.052Z [error]: ERROR: certificate has expired
CODE: CERT_HAS_EXPIRED
STACK: Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1140:34)
    at TLSSocket.emit (events.js:197:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node version: v11.9.0
 - npm version: 6.5.0
 - Udacimak Version: v1.3.0
 - Browser: Chrome

**Course Information**
 - Nanodegree or Course name: Neural Network Foundations Nanodegree Program
 - Version: v1.0.0
 - Locale: en-us

**Comment by udacimak** [comment]
@jaideepheer Could you please email the JSON data to udacimak@tutanota.com so I can inspect the issue?

**Comment by jaideepheer** [comment]
I have sent the email.

**Comment by udacimak** [comment]
@jaideepheer I was able to complete the render without problems.
Could you try rendering on a different computer/network?

**Comment by jaideepheer** [comment]
I don't know what happened but the issue is now fixed.

Thank you. 😅
