### ISSUE TITLE
Incorrectly generated index.html page

### ISSUE THREAD

**Issue by tigerjoy** [udacimak/udacimak#32]
The links to folders having "&" in their name, are not generated correctly. Say, the name of the folder is "Part 03-Module 01-Lesson 03_Arrays, Lists, Loops, & Custom Classes", then the corresponding HTML code generated for it is

` <a href="Part 03-Module 01-Lesson 03_Arrays, Lists, Loops,  Custom Classes/index.html">`

where as it should have been 

` <a href="Part 03-Module 01-Lesson 03_Arrays, Lists, Loops, & Custom Classes/index.html">`

Though not a app breaking bug and can be fixed with minor change to the index.html file, but  would appreciate if this problem is fixed. 

**Course Information**
 -  Android Basics Nanodegree
 - Version :v1.0.0
 - Locale:  en-us

**Comment by udacimak** [comment]
@tigerjoy I will fix this in a future release.
