### ISSUE TITLE
render command failed

### ISSUE THREAD

**Issue by TheBaby5** [udacimak/udacimak#33]
This is what the error m getting over and over again, it was working fine 3 days back, but now it seems to need an asap update! Udacity changed!

NOTE: I've also updated the youtube-dl to latest version, but it didn't worked! 

![image](https://user-images.githubusercontent.com/44883516/56848283-ac1edc00-6904-11e9-8153-91c834de3890.png)

**Comment by emmjaykay** [comment]
I believe I have a solution. If you do a 

`locate youtube-dl | grep bin`

You may find that there are separate youtube-dl installations. I had a full *three* separate installs somehow. One of them is the one that comes with udacimak.

To get it to run, do something like this

`~/.npm-packages/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl -U
`

You should see an update about the new 4.24.2019 edition being installed.

**Comment by udacimak** [comment]
@TheBaby5 I've released `v1.4.0` that fixes this issue.

**Comment by TheBaby5** [comment]
> @TheBaby5 I've released `v1.4.0` that fixes this issue.

**Thank you so much, it's working fine now after new update! <3**
