### ISSUE TITLE
Render ERROR: connect ETIMEDOUT

### ISSUE THREAD

**Issue by TheBaby5** [udacimak/udacimak#35]
**I've got the latest** `udacimak v1.4.0` **But still facing the ERROR: connect ETIMEDOUT while rendering the downloaded jason, please look into this...**

![image](https://user-images.githubusercontent.com/44883516/57076554-8e3be780-6d07-11e9-9220-a6a5aa6ed67d.png)

Copy-Paste of the error!

> x Download media file Man-Climbing-Up-in-Grocery-Store--115680.jpg
> 2019-05-02T12:47:36.654Z [error]: ERROR: connect ETIMEDOUT 169.48.71.26:443
> CODE: ETIMEDOUT
> STACK: Error: connect ETIMEDOUT 169.48.71.26:443
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1082:14)

**Comment by udacimak** [comment]
Could you please email the json file to udacimak@tutanota.com ? I will have a closer look when I have time.

**Comment by TheBaby5** [comment]
> Could you please email the json file to [udacimak@tutanota.com](mailto:udacimak@tutanota.com) ? I will have a closer look when I have time.

Done, please check your Inbox or Spam folder for the jason attached mail!

**Comment by udacimak** [comment]
Thanks, I'm experiencing the same issue. Will try to fix over the weekend.

If you want to manually fix the issue now, follow these steps:
- Open `data.json` file in `Part 09_Segmentation and Clustering/Module 03_Capstone Project/Lesson 01_Combining Predictive Techniques`
- Find the line that contains `http://www.freakingnews.com/pictures/115500/Man-Climbing-Up-in-Grocery-Store--115680.jpg`
- Replace `http://www.freakingnews.com/pictures/115500/Man-Climbing-Up-in-Grocery-Store--115680.jpg` with `https://s3.cn-north-1.amazonaws.com.cn/u-img/6c9b7378-6401-4a00-9b95-e31414c44276`
- Re-run `render` command

**Comment by TheBaby5** [comment]
Np, we'll wait! Can you resend me the updated jason file? Please that would be a great help!

**Comment by TheBaby5** [comment]
> Thanks, I'm experiencing the same issue. Will try to fix over the weekend.
> 
> If you want to manually fix the issue now, follow these steps:
> 
> * Open `data.json` file in `Part 09_Segmentation and Clustering/Module 03_Capstone Project/Lesson 01_Combining Predictive Techniques`
> * Find the line that contains `http://www.freakingnews.com/pictures/115500/Man-Climbing-Up-in-Grocery-Store--115680.jpg`
> * Replace `http://www.freakingnews.com/pictures/115500/Man-Climbing-Up-in-Grocery-Store--115680.jpg` with `https://s3.cn-north-1.amazonaws.com.cn/u-img/6c9b7378-6401-4a00-9b95-e31414c44276`
> * Re-run `render` command

**Thank you, it's working fine now!**

**Comment by teodargent** [comment]
I'm getting the same error.
`2019-06-20T10:54:20.218Z [info]: Completed rendering lesson file /media/teo/Cruzer/Predictive Analytics for Business Nanodegree  v1.0.0/Part 08-Module 02-Lesson 01_Combining Predictive Techniques/01. Project Overview.html
2019-06-20T10:54:20.218Z [info]: ____________________

✖ Download media file Man-Climbing-Up-in-Grocery-Store--115680.jpg
2019-06-20T10:56:31.439Z [error]: ERROR: connect ETIMEDOUT 169.48.71.26:443
CODE: ETIMEDOUT
STACK: Error: connect ETIMEDOUT 169.48.71.26:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
`


> Thanks, I'm experiencing the same issue. Will try to fix over the weekend.
> 
> If you want to manually fix the issue now, follow these steps:
> 
>     * Open `data.json` file in `Part 09_Segmentation and Clustering/Module 03_Capstone Project/Lesson 01_Combining Predictive Techniques`
> 
>     * Find the line that contains `http://www.freakingnews.com/pictures/115500/Man-Climbing-Up-in-Grocery-Store--115680.jpg`
> 
>     * Replace `http://www.freakingnews.com/pictures/115500/Man-Climbing-Up-in-Grocery-Store--115680.jpg` with `https://s3.cn-north-1.amazonaws.com.cn/u-img/6c9b7378-6401-4a00-9b95-e31414c44276`
> 
>     * Re-run `render` command

This is not in part 9 for me, it's in `Part 08_Segmentation and Clustering/Module 02_Capstone/Lesson 01_Combining Predictive Techniques`. 
Also, changing the url did not fixed the issue for me. I manually downloaded the image and placed it in `Part 08-Module 02-Lesson 01_Combining Predictive Techniques/img` and that worked.
