### ISSUE TITLE
Failed to download course: Cannot destructure property `lessons` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by emilylauyw** [udacimak/udacimak#36]
Thank you so much for sharing this! I am facing some issues with it, appreciate if you could advise how can I fix it.

**Describe the bug**
Received error message when trying to perform download and render

Error message when trying to download:
![01-1](https://user-images.githubusercontent.com/37318434/57383199-f182b980-71e0-11e9-8c8e-5f9d33ea6dfa.png)
![01-2](https://user-images.githubusercontent.com/37318434/57383207-f3e51380-71e0-11e9-9805-d90fa14f98bb.png)

Error message when trying to render:
![02](https://user-images.githubusercontent.com/37318434/57383076-c009ee00-71e0-11e9-9903-5ac2f65f339b.png)

*Desktop (please complete the following information):**
 - OS: Windows
 - Node version: Node version 10.15.3
 - npm version: npm version 6.4.1
 - Udacimak Version: udacimak version 1.4.0

**Comment by udacimak** [comment]
@emilylauyw 

### Download
Please let me know which course are you downloading that's throwing the error?

### Render
The path is not typed correctly, hence the error. Could you try:

```
udacimak render "_json\Data Analyst Nanodegree v7.0.0" -t C:\dand
```

**Comment by emilylauyw** [comment]
Hi @udacimak,

**Download**
I had the same error while trying to download from the following Nanodegree:
- Data Foundations
- Business Analyst
- Data Analyst Nanodegree

**Render**
Had tried the suggested path but still receiving error. Could it be because of the error msg I received when I run the download?
![image](https://user-images.githubusercontent.com/37318434/57451380-a4abeb00-7293-11e9-9112-3c27fc3d2755.png)
![image](https://user-images.githubusercontent.com/37318434/57451388-a8d80880-7293-11e9-9e5e-9b7c793cd171.png)

**Comment by udacimak** [comment]
### Download

Are there any Nanodegrees that you are able to download?
BTW, it's working on my end.

### Render

As long as you have downloaded the Nanodegree successfully, we can render.

Another way you can try is to rename the downloaded folder to NOT contain any spaces then re-run the `render` command without using double-quotes, eg:

```
udacimak render _json\DAND_v7.0.0 -t C:\dand
```

**Comment by emilylauyw** [comment]
**Download**
There are files downloaded even thou it had the error msg.
![01](https://user-images.githubusercontent.com/37318434/57452179-c908c700-7295-11e9-9163-f8e5859514dc.png)
![02](https://user-images.githubusercontent.com/37318434/57452184-ca39f400-7295-11e9-9550-bb9c62d5f398.png)

**Render**
Had tried rename but still having the same issue.
![image](https://user-images.githubusercontent.com/37318434/57452361-29980400-7296-11e9-977f-2728392664fe.png)

I have not idea what went wrong.

**Comment by udacimak** [comment]
I think there should not be an issue with `udacimak`.

Sorry, I'm not sure how to help. Could you try doing those again in a different folder path or computer?

**Comment by emilylauyw** [comment]
No worries, I will try doing it on another computer. Thanks.

**Comment by udacimak** [comment]
@emilylauyw Let me know how you go. If the problem persists and you find new causes to help us debug, please re-open this issue.
