### ISSUE TITLE
Video feature

### ISSUE THREAD

**Issue by thisisamank** [udacimak/udacimak#38]
Hi, i have a request for a feature that can significantly decrease the size of course downloaded. Since udacity uses youtube for their video so while downloading video through udacimak, instead of downloading the video can you add the youtube link and your video player will render the youtube video?

**Comment by udacimak** [comment]
Hi @thisisamank . I didn't consider this feature because I want the content to be completely usable offline.
Thanks for the suggestion but I don't have a plan to implement it.
