### ISSUE TITLE
Render error: CODE: ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by sstihler** [udacimak/udacimak#43]
**Describe the bug**
I am using `udacimak 1.4.0` and getting the following error.

```shell
2019-05-17T14:49:15.955Z [error]: TYPEERROR [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
CODE: ERR_INVALID_ARG_TYPE
STACK: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.extname (path.js:830:5)
    at downloadMediaInHtml (C:\Users\sstih\AppData\Roaming\npm\node_modules\udacimak\lib\commands\utils\downloadMediaInHtml.js:66:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The error is occurring at the time of rendering the course.
To download I have used: `udacimak download nd041`
There was no mistake.
To render I used: `udacimak render "Fundamentos Web Front-End v2.0.0"`
When it arrives in the folder 
`Fundamentos Web Front-End v2.0.0\Part 02-Module 01-Lesson 02_Lab - Sintaxe de HTML\08. Construindo links.html`
the error happens.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node version: `v10.15.3`
 - npm version: `6.4.1`
 - Udacimak Version: `v1.4.0`

**Course Information**
 - Nanodegree or Course name: Fundamentos Web Front-End nd-041
 - Version: v2.0.0
 - Locale: pt-br

**Comment by udacimak** [comment]
@sstihler Please email me the `data.json` files to udacimak@tutanota.com. I will have a look.

**Comment by udacimak** [comment]
@sstihler Could you please send me the `data.json` file of the lesson that's causing the issue? If you're not sure which one it is, please send me the whole Nanodegree's data.

**Comment by sstihler** [comment]
Em sex, 14 de jun de 2019 às 03:35, udacimak <notifications@github.com>
escreveu:

**Comment by udacimak** [comment]
@sstihler Please send the JSON files so I can have a look, or let me know if it's working for you.

**Comment by sstihler** [comment]
It does not work for me.


*Scheila Stihler*
 sstihler@gmail.com
 scheila.stihler
 +55 (48) 98464-5785




Em sex, 21 de jun de 2019 às 01:23, udacimak <notifications@github.com>
escreveu:

**Comment by sstihler** [comment]
Hello, have you still not been able to figure out what the problem is when you download the course?

**Comment by udacimak** [comment]
@sstihler Please send me the JSON files. I haven't received them yet.

**Comment by sstihler** [comment]
I already sent it twice. Which email should I send?
Follow attachment again.


*Scheila Stihler*
 sstihler@gmail.com
 scheila.stihler
 +55 (48) 98464-5785




Em sáb, 13 de jul de 2019 às 05:54, udacimak <notifications@github.com>
escreveu:

**Comment by udacimak** [comment]
@sstihler Please don't send the JSON files by replying to Github email, the attachment won't come through. Please email directly to udacimak@tutanota.com

**Comment by udacimak** [comment]
@sstihler Please send all the data.json files of the course instead as I've mentioned in a previous message. Thanks

**Comment by lucianobarauna** [comment]
Hi, I'm having the same problem. I'll attach the photo and send my date.json
![image](https://user-images.githubusercontent.com/1054454/61404935-fafa6300-a8ae-11e9-97ed-900d75664ebc.png)

Desktop (please complete the following information):

OS: Ubunut 18.04.2 LTS
Node version: v10.15.3
npm version: 6.4.1
Udacimak Version: v1.4.1
Course Information

Nanodegree or Course name: Nanodegree Desenvolvedor Web Full-Stack nd004-br
Version: v2.0.0
Locale: pt-br

**Comment by udacimak** [comment]
@lucianobarauna 
Thanks for the details. Please email all the `data.json`  the Nanodegree instead of just one file.

**Comment by lucianobarauna** [comment]
@udacimak 
I emailed the name and the link

**Comment by udacimak** [comment]
Thanks. I've been able to replicate the error and will fix it soon when I have time.

**Comment by udacimak** [comment]
@sstihler @lucianobarauna You can install the latest version to have this issue fixed.

**Comment by lucianobarauna** [comment]
@udacimak 
I was able to download it .. thank you very much
