### ISSUE TITLE
How do I change the resolution of the videos?

### ISSUE THREAD

**Issue by teodargent** [udacimak/udacimak#45]
How do I download the videos in 1080p instead of 720p? Thanks!

**Comment by udacimak** [comment]
The CLI use `youtube-dl` to download the videos. I've set the quality setting to be _best_. Not sure if it's getting the highest resolution video or not and if not, why, but I'll double check later.

**Comment by udacimak** [comment]
@teodargent For some reason, `youtube-dl` can only see the 720p video version. 
I've set the quality setting to `best` so I think that's the best quality we can get from Youtube.

If you have a better suggestion, feel free to reopen the issue.

**Comment by udacimak** [comment]
@teodargent I accidentally found out a way to download better video format, I'll release the update in the next coming update (coming soon).
The best video format will be downloaded by default, I still won't provide the option to change the quality option.

**Comment by teodargent** [comment]
Nice! Thank you!

**Comment by udacimak** [comment]
@teodargent Sorry, I didn't check carefully, downloading best video format resulting in video missing audio!
I'll have to roll back the changes soon.

**Comment by mhob** [comment]
Could this be reopened?

The proper format option for youtube-dl would be `--format='bestvideo+bestaudio/best'`

But what would be even better is if you could specify a format string. (For example, I personally prefer: `'bestvideo[ext=mp4][height<=1080][width<=1920]+bestaudio[ext=m4a]/mp4'` which gets me the best HD MP4 video.)

I tried messing with the code to make it work, but kept encountering issues. (I know zero JS, sorry.)

**Comment by abhiank** [comment]
Hello @udacimak. Thank you for this amazing tool. Its absolutely invaluable. 

I think there's still some issue with the video quality. For a course I downloaded, the majority videos are in 720p but some videos downloaded in 360p. Could you please take some time and re-look into it. Perhaps the latest suggestion from @mhob might help. Thank you!

**Comment by miguelusque** [comment]
Hi,

I am performing a test which seems to be working so far.

In this file:

https://github.com/udacimak/udacimak/blob/master/src/commands/utils/downloadYoutube.js

I have changed line #23 from:

`export default function downloadYoutube(videoId, outputPath, prefix, title, format = '22/18/17') {`

to:

`export default function downloadYoutube(videoId, outputPath, prefix, title, format = 'best/22/18/17') {`

Could someone else try the above? Thanks!

**Comment by rloterh** [comment]
@udacimak Video quality is still very bad. In the case of video demonstrating code or IDE, the writing are invisible. only '22' should be fine 
![image](https://user-images.githubusercontent.com/12745474/78506257-48fd1280-772d-11ea-8013-81ad57f2e858.png)
