### ISSUE TITLE
Please add capturing of project submissions

### ISSUE THREAD

**Issue by AeroGeekDean** [udacimak/udacimak#46]
First of all... I'm SO glad I found your project here! Just downloaded 7.25GB of my Self-Driving Car Engineering ND (orig Ver 1.0 of the ND, which consists of 3 terms. Udacity reduced it down to only 2 terms later on by removing some materials.)
**THANK YOU!!!**

**Is your feature request related to a problem? Please describe.**
One thing I did not see captured is my submitted project reviews.

Looking at the very bottom of Udacity's project page (usually the last page within the project lesson, which your tool already captured), there's a line that read

> _Congratulations! You've completed this project_

with a **[view submission]** button next to it.

When clicking that button, a new browser page opens up that contains my project submission + reviewer feedbacks. Often the feedback contains very useful info & links (to additional resources) that would be good to capture as well.

The url of the review page has the following format: `https://review.udacity.com/#!/reviews/SOME_5_TO_7_DIGIT_NUMBER`

**Describe the solution you'd like**
Is it possible to also capture the project contents from the review.udacity.com page(s)?

**Describe alternatives you've considered**
The less desirable alternative is to capture the unique url link that opens up the project review on `review.udacity.com` site, and leave the content availability to the mercy of Udacity (hoping they don't remove it in the future).

**Additional context**
Below is screenshot of the [view submission] button at bottom of the project submission page.
![Screenshot 2019-06-20 11 44 24](https://user-images.githubusercontent.com/7883860/59873972-0a3ecd00-9352-11e9-8c2e-def526723ea4.png)

Thanks again!
-Dean

**Comment by udacimak** [comment]
Thanks @AeroGeekDean 

I decided not to develop this feature due to time constraints.

Outputting project review is a bit complicated due to the _Code Review_ section, which requires showing each code file with their comments. This will require downloading the project, open the code files, generating HTML, embedding the comments into them, etc.

**Comment by AeroGeekDean** [comment]
@udacimak
Ah, gotcha! Ok, now that you mentioned it... I could definite see the complexity of this now. (My background is in mech/aero engineering. I can design some airplane autopilots & rockets for you. But I'm pretty much clueless on web related technologies! 😆)

---
Given that, perhaps I could ask for some recommendations/advices from you on how I could preserve these myself...?

Currently, I've bookmarked the url of all of my submitted project reviews. Thus I could access them off Udacity's server... for now. 

For my situation, I had near zero _CODE REVIEW_ comments. Majority of the feedback contents are within the _REVIEW_ section. (Of 13 submitted projects, only had 1 code review feedback. And THAT only contained 5 brief comments.)

I tried to '_Save Page As..._' from my browser (Mac/Chrome) with no success. If save `html only`, I got a blank page. if save `complete`, the local `.htm` file opens up to a 404 error. (I'm guessing the original actual page was doing some sort of dynamic query into Udacity's API, that browser save doesn't capture.)

If I browser: print->pdf, I could capture the text. But any embedded links are lost. I would like to capture both. Is there a way I could do this? (short of manually saving the embedded url via browser bookmarking)

thanks!

**Comment by AeroGeekDean** [comment]
@udacimak 
Oh, disregard my prior...!!!

Turns out that `Mac/Safari: print->pdf` **does** preserve embedded links!
I'll just preserve my submitted project reviews that way then! 😊

**Comment by udacimak** [comment]
:smile: Wish I had time to develop that, too. But I hardly got time to provide more features to `udacimak` now.

**Comment by AeroGeekDean** [comment]
> 😄 Wish I had time to develop that, too. But I hardly got time to provide more features to `udacimak` now.

No worries. Totally understand!

What you've done with `udacimak` thus far is already an **EXCELLENT** resource for alumni! Thanks much!!!
