### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by TheBaby5** [udacimak/udacimak#49]
**Screenshots**

![image](https://user-images.githubusercontent.com/44883516/61888024-6633dd00-af20-11e9-972c-aaab61559a23.png)

**Describe the bug**

While I was trying to render downloaded jason got this error!

ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by
HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call yo
utube-dl with the --verbose flag and include its complete output.

**To Reproduce**

x Getting Youtube video id snxmBgi_GeU information
2019-07-25T15:29:45.500Z [error]: ERROR: Command failed: C:\Users\Administrator\
AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl
.exe --dump-json --format=best --encoding utf8 http://www.youtube.com/watch?v=sn
xmBgi_GeU
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by
HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call yo
utube-dl with the --verbose flag and include its complete output.

CODE: 1
STACK: Error: Command failed: C:\Users\Administrator\AppData\Roaming\npm\node_mo
dules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json --format=b
est --encoding utf8 http://www.youtube.com/watch?v=snxmBgi_GeU
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by
HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you
are using the latest version; type  youtube-dl -U  to update. Be sure to call yo
utube-dl with the --verbose flag and include its complete output.

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)

D:\RIP\Google>

**Udacimak Log**
Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:

```shell
2019-07-25T15:22:26.166Z [[31merror[39m]: ERROR: Target directory doesn't exist. Please create the directory "D:RIPUdacity"
STACK: Error: Target directory doesn't exist. Please create the directory "D:RIPUdacity"
    at renderCourse (C:\Users\Administrator\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:36:11)
2019-07-25T15:29:45.500Z [[31merror[39m]: ERROR: Command failed: C:\Users\Administrator\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json --format=best --encoding utf8 http://www.youtube.com/watch?v=snxmBgi_GeU
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

CODE: 1
STACK: Error: Command failed: C:\Users\Administrator\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json --format=best --encoding utf8 http://www.youtube.com/watch?v=snxmBgi_GeU
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)

```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows Server]
 - Node version: (`v12.1.0`)
 - npm version: (`6.9.0`)
 - Udacimak Version: (`v1.4.4`)
 - Browser [chrome]

**Course Information**
 - PyTorch Scholarship Challenge Nanodegree Program
 - Version: PyTorch Scholarship Challenge  v1.0.0
 - Locale: [en-us]

**Comment by udacimak** [comment]
@TheBaby5 The Too Many requests error means there are too many requests being sent to the server so the request is rejected.

It should work if you try again after a short wait.

**Comment by TheBaby5** [comment]
**Sure, I'll retry and update.**

**Comment by TheBaby5** [comment]
**Sorry, it's still the same! Same error is popping!**

**Comment by TheBaby5** [comment]
**I've got one workaround, by using VPN/Proxy service the issue seems to be solved... Currently using dedicate proxy.**
