### ISSUE TITLE
Subtitles/closed caption on rendered video

### ISSUE THREAD

**Issue by nuges01** [udacimak/udacimak#5]
Hi,

The rendered video doesn't seem to have an option to turn on subtitles/closed caption. Is this a function of the video player or a bug? If it's the video player, do you have tips for configuring with a subtitle-supporting player?

Thanks!

**Comment by udacimak** [comment]
Hi @nuges01,

I didn't write HTML5 support for video subtitles. HTML5 video player requires the web page to be run on a server to display the subtitles, so I didn't think of supporting it due to the server hassle.

If you prefer to have subtitles, you can use [VLC](https://www.videolan.org) to watch the videos with subtitles instead.

**Comment by hantatsang** [comment]
@nuges01 I feel like, since the CLI downloads subtitles, it's a waste not to display subtitles on the webpage.

I'll add this feature and release an update.
I'll let you know once a new version is released, should be in less than a day.

**Comment by udacimak** [comment]
@nuges01 
Since the CLI download subtitles, I think it's a waste not to display subtitles on the webpage.

I'll add subtitles feature and release an update. I'll let you know once a new version is released, should be in less than a day.

**Comment by udacimak** [comment]
I have released a new version that includes subtitles in the HTML code.
See [here in `README`](https://github.com/udacimak/udacimak/blob/master/README.MD#watching-video-with-subtitles#watching-video-with-subtitles) for details.

If any further problems, please let me know.

Enjoy!

**Comment by nuges01** [comment]
This is awesome work, @udacimak. The entire tool is just so amazing. You, sir/ma'am deserve a medal!

**Comment by mendax-iitm** [comment]
Using Visual Studio Code to open root directory of the project and just setup the server.....and subtitles are visible....Awesome work by @udacimak

**Comment by MohammedEl-sayedAhmed** [comment]
@abhinitrpr @udacimak Could you please illustrate in more details how can I view the subtitles while I am viewing the material in html page. 
I already downloaded the nanodegree and the subtitle files exist but I can't view them on the video  
![image](https://user-images.githubusercontent.com/57391064/108917565-9d0c3080-7638-11eb-931f-8a2d2e650a79.png)

**Comment by azhafidh** [comment]
helooo, i still cant use the subtitle
