### ISSUE TITLE
Option to skip youtube downloads

### ISSUE THREAD

**Issue by shahidcodes** [udacimak/udacimak#51]
**Is your feature request related to a problem? Please describe.**
As all nano degree uses youtube unlisted video so I feel it is unncessary to download all videos locally. And in low FUP bandwidth internet connection it becomes difficult to download all videos past FUP.
**Describe the solution you'd like**
Add an option to switch off the downloads and render embedded youtube video player instead.

**Comment by udacimak** [comment]
Thanks @shahidcodes 
I built the CLI with the intention to make the course fully functional without requiring online resources.
Unfortunately, I'm not planning to develop your proposed feature.
