### ISSUE TITLE
Skip Subtitles Download

### ISSUE THREAD

**Issue by awaissaeed530** [udacimak/udacimak#52]
Downloading subtitles in some courses takes a lot of time because each video has 10-15 subtitles files and some have even more. While I don't even want to download any subtitle file I think there should be feature to skip subtitles during render process.

**Comment by udacimak** [comment]
@awaissaeed530 I will plan this for a future release, but no concrete timeline yet.

**Comment by omar5050** [comment]
how can i add subtitle to video in browser
