### ISSUE TITLE
Unable to render

### ISSUE THREAD

**Issue by ravireddy07** [udacimak/udacimak#53]
I've downloaded the json files in Documents,
i used the command `udacimak render C:\username\Documents\Nanodegree_name`,

It showing the error that _ERROR: Path to downloaded Udacity course/Nanodegree doesn't exist.
STACK: Error: Path to downloaded Udacity course/Nanodegree doesn't exist.
    at renderCourse _
[udacimak.info.log](https://github.com/udacimak/udacimak/files/3515915/udacimak.info.log)
[udacimak.error.log](https://github.com/udacimak/udacimak/files/3515916/udacimak.error.log)

**Comment by udacimak** [comment]
Hi @ravireddy07 ,

It seems you're using Windows, you need to put the path into double quotes because of the space characters, eg. `udacimak render "C:\username\Documents\Nanodegree_name"`

**Comment by ravireddy07** [comment]
Yes...It worked..!!!
