### ISSUE TITLE
Add delay/sleep between youtube downloads

### ISSUE THREAD

**Issue by jrao1** [udacimak/udacimak#54]
Youtube is starting to crackdown on automated downloader, I'm getting "HTTP Error 429: Too Many Requests" after a few downloads using udacimak, see also: https://github.com/ytdl-org/youtube-dl/issues/21729

Seems like the only way to avoid this is to have delay/sleep between youtube downloads, I added a 300s delay and skipped subtitle downloading, this seems to be working so far.

Please consider adding the delay/sleep value as a command line parameter, together with https://github.com/udacimak/udacimak/issues/52 it should make youtube download possible again.

PS: I tried to put youtube-dl's --sleep-interval parameter in /etc/youtube-dl.conf, but it doesn't seem to have any effect when using udacimak.

**Comment by udacimak** [comment]
Thanks @jrao1 
I'm pretty busy at the moment but will try to fix this asap for the next release

**Comment by udacimak** [comment]
Sorry for the delay, I'm super busy but will be able to have a look at this within the next few weeks.

**Comment by udacimak** [comment]
@jrao1 @nico00  I'm looking at this problem.

But by looking at this post:
- https://github.com/ytdl-org/youtube-dl/issues/21729#issuecomment-511085253

I see that adding a delay between downloads doesn't really fix the issue. 

It's strange because I don't encounter this issue at all. Will it help by using a VPN in your situation?

**Comment by jrao1** [comment]
@udacimak Yes, I have read that comment, I think his delay is not long enough, I tried 300s delay which seems to work well. VPN is a lot of hassle to setup, so I'd like to avoid it if possible.

**Comment by udacimak** [comment]
@jrao1 OK I'll add the option for delay soon and will release an update.

**Comment by udacimak** [comment]
@jrao1 Release is published, you can use the delay as in this example:

```shell
udacimak render path-to-nd -d 5
# or
udacimak render path-to-nd --delay-youtube 5
```

This will add 5-second delay between each Youtube download
