### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by jackinDev** [udacimak/udacimak#58]
While rendering the json file of the Natural Language Processing nanodegree it shows the following error:

udacimak render "/Users/aroop/Natural Language Processing Nanodegree v1.0.0/data.json" "/Users/admin/Study/nlp"

2019-10-18T09:15:54.631Z [error]: TYPEERROR: Cannot read property 'length' of undefined
STACK: TypeError: Cannot read property 'length' of undefined
    at renderCourse (/Users/admin/.nvm/versions/node/v10.16.3/lib/node_modules/udacimak/lib/commands/render/functions/renderCourse.js:55:48)

 - OS: [e.g. iOS] MacOS
 - Node version: (`node --version`) v10.16.3
 - npm version: (`npm --version`) 6.9.0
 - Udacimak Version: (`udacimak --version`) v1.4.5
 - Browser [e.g. chrome, safari] chrome

**Course Information**
 - Nanodegree or Course name: Natural Language Processing Nanodegree 
 - Version: [e.g. v1.0.0] v1.0.0
 - Locale: [e.g. en-us]

**Comment by udacimak** [comment]
Hi @jackinDev 
Please email the JSON files to udacimak@tutanota.com so I can have a look.

**Comment by udacimak** [comment]
@jackinDev I've been able to render the Nanodegree without issues.

Please fix the command as such:

```
udacimak render "/Users/aroop/Natural Language Processing Nanodegree v1.0.0" "/Users/admin/Study/nlp"
```

There's no need to include `data.json` in the path
