### ISSUE TITLE
There is no subtitles in vedio for showing

### ISSUE THREAD

**Issue by Er0x05** [udacimak/udacimak#61]
Download is okay.
Render with --subtitles is okay.
I got all of files videos and subtitles.
But there is no subtitles in vedeo after click the 'CC' button.

May I get any help?  thanks so much.

**Comment by udacimak** [comment]
@Er0x05 
Browsers have a policy that blocks loading subtitle files if HTML files are opened directly (with `file://` uri)
To watch with subtitles you'll need to serve the HTML files on localhost (one option is to use https://www.npmjs.com/package/serve )

**Comment by Er0x05** [comment]
> @ Er0x05
> 浏览器有一个策略，如果直接打开HTML文件（使用`file://`uri），则阻止加载字幕文件。
> 要观看字幕，您需要在localhost上提供HTML文件（一种选择是使用[https：//www.npmjs。 com / package / serve](https://www.npmjs.com/package/serve)）

thanks . It works. =]
