### ISSUE TITLE
cannot locate 'youtube-dl'

### ISSUE THREAD

**Issue by PuRp1eWind** [udacimak/udacimak#62]
**Describe the bug**
when I use `udacimak settoken`, I get an error:

throw new Error('ERROR: unable to locate `youtube-dl` at ' + binPath)

Error: ERROR: unable to locate `youtube-dl` at 

**Desktop (please complete the following information):**
 - OS: macOS 10.15.1
 - Node version: v13.1.0
 - npm version: 6.12.1
 - Udacimak Version: when I run `udacimak --version`, I get the same error
<img width="1047" alt="Screen Shot 2019-11-10 at 2 42 00 PM" src="https://user-images.githubusercontent.com/32575757/68540140-4558a000-03c8-11ea-9216-2a926ca33471.png">

**Comment by PuRp1eWind** [comment]
I followed the install guide on the wiki page.

**Comment by udacimak** [comment]
That's a strange issue. Could you try on a different machine to see if it works?

**Comment by PuRp1eWind** [comment]
I can not solve this issue. I'm using the docker version of udacimak. However, I don't know the default download folder path. I'm using `docker container run -it -v "$(pwd)/:/downloads" udacimak/udacimak download xxx`. Any suggestions?

**Comment by PuRp1eWind** [comment]
I run this command ` docker container run -it -v "/Users/wangtongtong/Downloads/Learning/MOOC/Udacity" udacimak/udacimak  download --targetdir /Users/wangtongtong/Downloads/Learning/MOOC/Udacity ud827 ud359 cs271 ud600 ud730 cs373 ud501`    
I can download JSON data. But I don't know where these data is. There is nothing in the /Users/wangtongtong/Downloads/Learning/MOOC/Udacity folder

**Comment by PuRp1eWind** [comment]
I think the wiki page needs to clarify the default download and render folder paths.

**Comment by udacimak** [comment]
> I run this command ` docker container run -it -v "/Users/wangtongtong/Downloads/Learning/MOOC/Udacity" udacimak/udacimak download --targetdir /Users/wangtongtong/Downloads/Learning/MOOC/Udacity ud827 ud359 cs271 ud600 ud730 cs373 ud501`
> I can download JSON data. But I don't know where these data is. There is nothing in the /Users/wangtongtong/Downloads/Learning/MOOC/Udacity folder

You need to be familiar with Docker Volume to get the data to your local machine. Though I've seen Docker on Windows having issues with volume before - it doesn't connect to the volume properly - but I'm not a DevOps expert so I'm not sure how to resolve that.

**Comment by akashbisht81** [comment]
Me too, I am having this issue on my windows 10. same kind of issue.

**Comment by vsay01** [comment]
The same issue installed with npm install -g udacimak

**Comment by vsay01** [comment]
@udacimak is it working on your machine when you install from npm package?

**Comment by udacimak** [comment]
@vsay01 yes it works on all my computers. I haven't been able to replicate this issue yet. I'd suggesting trying using `nvm`, Docker image, changing OS. Let me know if any of those work?

**Comment by vsay01** [comment]
@udacimak I use udacimak docker and it's working. For now I'll keep using docker version, Thanks
