### ISSUE TITLE
Target Directory/Path To downloaded Udacity not exist. 

### ISSUE THREAD

**Issue by rupeshvins** [udacimak/udacimak#66]
**Render is not working**

Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:

```shell
INSERT_LOG_HERE
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 8.1 Enterprise]
 - Node version: (`node --v13.0.1`)
 - npm version: (`npm --version`)
 - Udacimak Version: (`udacimak --1.4.5`)
 - Browser [chrome]

**Course Information**
 - Nanodegree or Course name: [Bertelsmann Tech Scholarship Challenge Course - AI Track Nanodegree Program]
https://classroom.udacity.com/nanodegrees/nd188-bert
 - Version: [e.g. v1.0.0]
 - Locale: [e.g. en-us]

**_Course is download in C:\Users\Vins directory_**

![json files](https://user-images.githubusercontent.com/7515562/70027476-40060400-15c8-11ea-9352-59dd9d50477e.JPG)

How to use this structure plz give example 
![how to save](https://user-images.githubusercontent.com/7515562/70040210-27561800-15e1-11ea-91a4-d44ecd0396ef.JPG)

**Additional context**
1. When I use $ udacimak render _json\Bertelsmann Tech Scholarship Challenge Course - AI Track v1.0.0 -t C:\Users
Got error -->Target directory doesn't exist. Please create the directory
![target direcotry missing](https://user-images.githubusercontent.com/7515562/70027500-4bf1c600-15c8-11ea-9499-59a4e7a48a66.JPG)

2. When I use-->  $ udacimak render _json\Bertelsmann Tech Scholarship Challenge Course - AI Track v1.0.0 -t "C:\Users"
 Path to downloaded Udacity course/Nanodegree doesn't exist.
![After double](https://user-images.githubusercontent.com/7515562/70027522-544a0100-15c8-11ea-9d8d-2afef8a5df83.JPG)

3. I remove space between download folder then it shows target directory doesn't exist.

plz show me where I make mistake.
Thanks

**Comment by udacimak** [comment]
@rupeshvins On Windows, uou need to make sure to wrap all paths that have space characters inside double quotes

**Comment by rupeshvins** [comment]
Hi
I make no space b/w download file, but error still comes
![wrappath](https://user-images.githubusercontent.com/7515562/70049037-c71ba200-15f1-11ea-82af-6b38ff0dedda.JPG)

**Comment by rupeshvins** [comment]
Plz find all json data, folder is not so I make zip
thanks

**Comment by udacimak** [comment]
@rupeshvins You need to run the command as this example:

```
udacimak render "_json\Bertelsmann Tech Scholarship Challenge Course - AI Track v1.0.0" -t "C:\Users"
```

I'm not on Windows at the moment so I can't double check but it should look like that - please search on Windows cmd with space character for help

**Comment by rupeshvins** [comment]
Hi, I make in another laptop but same directory not found, can I raise a request here, can u download https://classroom.udacity.com/courses/ud188 and share via google drive with me.
Thanks

**Comment by udacimak** [comment]
@rupeshvins Please email me your JSON data to udacimak@tutanota.com , I can have a look and download

**Comment by udacimak** [comment]
@rupeshvins any update?

**Comment by rupeshvins** [comment]
No same problem, target directory didn't found.

**Comment by rupeshvins** [comment]
I send u soon json data

**Comment by rupeshvins** [comment]
Udacimak not working, plz try other methods.
Even I try all Udacimak method and Dockers but no result

**Comment by maladeep** [comment]
Guys, It worked for me when I ran the command like this example:

`udacimak render "Bertelsmann Tech Scholarship Challenge Course - AI Track v1.0.0" `

i.e
`udacimak render "<YOUR UDACITY COURSE DIRECTORY NAME AS IT IS> " `

**Comment by rupeshvins** [comment]
can u show the screen shot when it run

**Comment by pratikwatwani** [comment]
Seems that I have the same issue on Mac.

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/16489964/77697872-077aa380-6f86-11ea-8056-874313bdec42.png">
