### ISSUE TITLE
In Docker toolbox user key and course download

### ISSUE THREAD

**Issue by rupeshvins** [udacimak/udacimak#67]
**Describe the bug**
In Docker command prompt user key and course download error comes

**Udacimak Log**
Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:

```shell
INSERT_LOG_HERE
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 8]
Docker toolbox v19.03.1
 - Node version: (`node --version`)
 - npm version: (`npm --version`)
 - Udacimak Version: (`1.4.5`)
 - Browser [chrome]

**Course Information**
 - Bertelsmann Tech Scholarship Challenge Course - AI Track Nanodegree Program
 - Version:

**Additional context**
Userkey error
![docker user](https://user-images.githubusercontent.com/7515562/70047698-88d0b380-15ee-11ea-8a99-8da3f7a21486.JPG)

Course download error 
$udacimak download ud188
![course error](https://user-images.githubusercontent.com/7515562/70047815-d1886c80-15ee-11ea-91f3-de500a2f566b.JPG)

plz sort out the problem

**Comment by udacimak** [comment]
@rupeshvins This is due to the pasted JWT token is not correct. Please also don't post screenshots of  your JWT token - it is your private credential

**Comment by rupeshvins** [comment]
Hi
I cross chk JWT token in chrome and firefox both show same key 80-90 character, so key is correct and I didn't post full key with snapshot.

**Comment by udacimak** [comment]
Please try again, also please make sure there are no white space after the JWT token. Occasionally, it's a bit tricky working on Windows CMD

**Comment by rupeshvins** [comment]
Udacimak not working, plz try other methods.
Even I try all Udacimak method and Dockers but no result
