### ISSUE TITLE
 Command failed with exit code 3

### ISSUE THREAD

**Issue by Hanson7300** [udacimak/udacimak#68]
**Describe the bug**
Hi, I tried many times to re-install npm, udacimak, etc , fix that''Unhandled Promise Rejection Error'', and i got this new error message:

**Screenshots**
![Snipaste_2019-12-05_21-37-17](https://user-images.githubusercontent.com/22568493/70240211-c298ea00-17a7-11ea-8729-0d22b113e15e.png)

**Desktop (please complete the following information):**
 - OS: [windows10 1909]
 - Node version: (`12.13.0`)
 - npm version: (`6.12.0`)
 - Udacimak Version: (`1.4.5`)
 - Browser [chrome]

**Course Information**
 - Nanodegree or Course name: [Android Basic Nanodegree]
 - Version: [1.0.0]
 - Locale: [zh-cn]

**Comment by rupeshvins** [comment]
@Hanson7300 
Hi, I also face same error in windows via github, but u use which s/w ? Is ur's json downloaded file in Android folder or in Hanson? 
in Github I use  udacimak _json\Name of folder where json file located (I dont knew this is correct way to call json file)
Plz reply

**Comment by Hanson7300** [comment]
@rupeshvins 
The json file is in the Android folder.The auto generate folder name contains Chinese character,I rename it just for convenience.And what do you mean by s/w? 
On windows 10 I use` udacimak render C:\Users\Hanson\Android -t C:\Users\Hanson\Desktop ` and some index html files renders correctly(see the picture above),so i guess that's correct. I think the render priority is the same,so if your index html downloaded correctly,then your command is correct.

**Comment by udacimak** [comment]
@Hanson7300 Are you rendering from China? Could you try using a VPN?

**Comment by udacimak** [comment]
@Hanson7300 Please email me the JSON files so I can try rendering the course - udacimak@tutanota.com
