### ISSUE TITLE
can't re-render

### ISSUE THREAD

**Issue by jacky-ttt** [udacimak/udacimak#7]
I receive below error when I try to re-render a course using command `udacimak render "React v1.0.0"`.   
```
2018-11-16T06:45:50.712Z [[31merror[39m]: ERROR: ENOENT: no such file or directory, open 'React v1.0.0\assets\css\fonts\data.json'
CODE: ENOENT
STACK: Error: ENOENT: no such file or directory, open 'React v1.0.0\assets\css\fonts\data.json'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at writeHtmlLesson (C:\Users\miu-razor\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlLesson.js:38:26)
    at renderCourse (C:\Users\miu-razor\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:115:45)
```

I am on Window, using udacimak v1.2.0
The file `data.json` is indeed absent.

**Comment by jacky-ttt** [comment]
since the `--targetdir` is optional, the downloaded and render content live in the same directory, "React v1.0.0". Does it mean that `--targetdir` should not be optional?

**Comment by udacimak** [comment]
Yes `--targetdir` is optional. But we shouldn't put downloaded and rendered content in the same directory.

For example, I like to structure my content as such:

```
udacimak
├── _json
│   ├── React v1.0.0
│   │   ├── (This folder contains downloaded JSON data)
├── React v1.0.0
│   ├── (This folder contains rendered contents)
```

The downloaded and rendered folders must be separated.

**Comment by jacky-ttt** [comment]
OK. I tried your directory structure. It does work. 
But when I put like this:
```
udacimak
├── React v1.0.0
│   ├── (This folder contains downloaded JSON data)
│   │   ├── render
│   │   │   ├── React v1.0.0 (Somehow created for me)
│   │   │   │   ├── (This folder contains rendered contents)
```
The error will occur. Looks like it must follow your ideal directory structure; otherwise, it will fail.

**Comment by udacimak** [comment]
You're right. 
The structure of the downloaded JSON folder should not be modified because the `render` command blindly looks for `data.json` in every folder, it will throw the error if a folder doesn't contain `data.json`

**Comment by avrdan** [comment]
Why is this issue closed? The README is still not clear about this! IMO the `--targetdir` should NOT be optional.
