### ISSUE TITLE
 Command failed with exit code 3221225595

### ISSUE THREAD

**Issue by AhmdNassar** [udacimak/udacimak#70]
**Describe the bug**
when I run udacimake render I get this error ERROR: Command failed with exit code 3221225595

**Screenshot** 

![image](https://user-images.githubusercontent.com/26696536/71141696-b1c38c00-221d-11ea-9383-f89eee55ee60.png)

when I tried to render ND again I get this error : ERROR: ENOENT: no such file or directory, open 'assets\css\fonts\data.json'

**Screenshot**
![image](https://user-images.githubusercontent.com/26696536/71141753-d7e92c00-221d-11ea-9099-43c94638d6fa.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Node version: (`12.7.0`)
 - npm version: (`6.10.0`)
 - Udacimak Version: (`1.4.5`)
 - Browser [chrome]

**Course Information**
 - Nanodegree or Course name: [Robotics Software Engineer Nanodegree]
 - Version: [v1.0.0]
 - Locale: [ar-eg]

**Comment by udacimak** [comment]
@AhmdNassar For the second issue, please separate render and download folder first, see here:
- https://github.com/udacimak/udacimak/wiki/How-to-Use#important-render-directory-note

Could you try that and see if the Youtube download issue persist?

**Comment by AhmdNassar** [comment]
@udacimak I tried to separate render and download folder but the same error

![image](https://user-images.githubusercontent.com/26696536/71260623-fa756500-2343-11ea-8269-507dd1e8d900.png)

**Comment by udacimak** [comment]
@AhmdNassar This is a different issue. Could you please send me the downloaded JSON files to udacimak@tutanota.com so I can check on my end.

**Comment by AhmdNassar** [comment]
@udacidown I sent JSON file to your mails.

**Comment by udacimak** [comment]
@AhmdNassar I can render the Nanodegree normally without issues on my end.
I'm not sure what's causing that error.
Does this error occurs for you when downloading other courses, too?
I'd also suggest trying to run Udacimak in a Docker container (if you're familiar with Docker)

**Comment by AhmdNassar** [comment]
I didn't try to download other courses, I will try, but I'm
an enterprise student with NTL in Egypt so am I allowed to download
Nanodegree? or this could be the problem!

unfortunately, I'm not familiar with Docker

**Comment by udacimak** [comment]
You should be able to download - the error is with downloading Youtube videos. Let me know how you go.
