### ISSUE TITLE
Cannot read property 'lessons' of undefined

### ISSUE THREAD

**Issue by Abhishekdm** [udacimak/udacimak#73]
$ udacimak render "C:\Users\abhishek\Desktop\Intel® Edge AI Scholarship Foundation Course v1.0.0\Part 02_Intel® Edge AI Foundation Course\Module 01_Intel® Edge AI Foundation Course\Lesson 
 01_Introduction to AI at the Edge" -t "coursedownload"
2020-01-22T15:54:25.897Z [error]: TYPEERROR: Cannot read property 'lessons' of undefined
STACK: TypeError: Cannot read property 'lessons' of undefined
    at writeHtmlCourseSummary (C:\Users\abhishek\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\writeHtmlCourseSummary.js:92:66)
    at async renderCourse (C:\Users\abhishek\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\functions\renderCourse.js:83:3)
    at async render (C:\Users\abhishek\AppData\Roaming\npm\node_modules\udacimak\lib\commands\render\index.js:20:5)

i keep getting the above error
i have attached a screenshot for reference
im on windows
![Annotation 2020-01-22 213053](https://user-images.githubusercontent.com/22396053/72910488-9983e700-3d5e-11ea-96b5-7d196ae60aa5.jpg)

**Comment by udacimak** [comment]
@Abhishekdm Please send me the JSON files to udacimak@tutanota.com so I can have a look

**Comment by Abhishekdm** [comment]
> @Abhishekdm Please send me the JSON files to [udacimak@tutanota.com](mailto:udacimak@tutanota.com) so I can have a look

i have sent you the json file as an email.

**Comment by Abhishekdm** [comment]
i have  attached the whole folder as a rar file.

**Comment by udacimak** [comment]
@Abhishekdm I have not received the full JSON files, could you please send again?

**Comment by udacimak** [comment]
@Abhishekdm I'm able to render the course without issues.

Can you try running this command:

```
udacimak render "C:\Users\abhishek\Desktop\Intel® Edge AI Scholarship Foundation Course v1.0.0" -t "coursedownload"
```

Note that render points to the folder that contains the downloaded content, not to a specific lesson

**Comment by 1871vinayak** [comment]
@Abhishekdm @udacimak 
Could you please send me the JSON files to sk20011999@gmail.com so that i can test it on workspace for any issue..

**Comment by udacimak** [comment]
I'm closing this issue, it can be resolved as below

> @Abhishekdm I'm able to render the course without issues.
> 
> Can you try running this command:
> 
> ```
> udacimak render "C:\Users\abhishek\Desktop\Intel® Edge AI Scholarship Foundation Course v1.0.0" -t "coursedownload"
> ```
> 
> Note that render points to the folder that contains the downloaded content, not to a specific lesson
