### ISSUE TITLE
incorrect html formatting of covariance matrix multiplication

### ISSUE THREAD

**Issue by ememdev** [udacimak/udacimak#74]
I'm running the latest version, v1.4.5 - updated yesterday.

I'm saving down the AI for Trading ND (880) and noticed that the rendered HTML page seems to be incorrectly formatting Covariance Matrix multiplication.

The left-justification is fine, it's the formatting of the matrices showing multiplication that is different; seems to be missing a newline? After a download & render, I'm seeing this:

> ![Screen Shot 2020-01-26 at 10 21 46 AM](https://user-images.githubusercontent.com/42899561/73137425-bc93ec80-4025-11ea-916f-ff4a2dd173b8.png)

whereas the online lesson shows this:

> ![Screen Shot 2020-01-26 at 10 22 39 AM](https://user-images.githubusercontent.com/42899561/73137433-e9e09a80-4025-11ea-980a-071907a82140.png)

**Comment by udacimak** [comment]
@ememdev Thanks for reporting the issue.

It was very difficult for me to render the Latex syntax that are written on Udacity. I believe their syntax is a bit messy, which led to Udacimak's parser having trouble rendering some of the syntaxes.

I'm not able to fix this at the moment as it has become too hacky to render their Latex syntax, but I will try to have a look when I have a chance.

**Comment by udacimak** [comment]
Closing this issue because:

- Latex syntax in Udacity's JSON data is not consistent - it's not possible to improve at this moment.
