### ISSUE TITLE
Not able to download content

### ISSUE THREAD

**Issue by tavishjain** [udacimak/udacimak#75]
**Describe the bug**
2020-02-03T19:22:57.919Z [error]: TYPEERROR: Cannot read property 'length' of undefined
STACK: TypeError: Cannot read property 'length' of undefined
    at renderCourse (/usr/local/share/.config/yarn/global/node_modules/udacimak/lib/commands/render/functions/renderCourse.js:55:48)

**To Reproduce**
Ran the following command after setting token
udacimak render nd893-ent

**Expected behavior**
Should have started downloading

**Udacimak Log**
Relevant portion of the logs from `udacimak.info.log`
and/or `udacimak.error.log` files:

```shell
INSERT_LOG_HERE
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu (Every software is in latest version below)
 - Node version: (`node --version`)
 - npm version: (`npm --version`)
 - Udacimak Version: (`udacimak --version`)

**Course Information**
 - Nanodegree or Course name: [Deep Reinforcement Nanodegree
 - Version: v1.0.0
 - Locale: en-us

**Additional context**

**Comment by udacimak** [comment]
@tavishjain From which directory do you run the `render` command?
