### ISSUE TITLE
Command failed with exit code 3221225781

### ISSUE THREAD

**Issue by ayushbathrey** [udacimak/udacimak#78]
It was working fine till 08-02-2020, I formatted my pc yesterday and now it has stopped working.
ERROR LOG:
2020-02-10T05:41:48.445Z [[31merror[39m]: ERROR: Command failed with exit code 3221225781: C:\Users\Ayush\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json --format=best --encoding utf8 http://www.youtube.com/watch?v=7kphieW4yl4
STACK: Error: Command failed with exit code 3221225781: C:\Users\Ayush\AppData\Roaming\npm\node_modules\udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json --format=best --encoding utf8 http://www.youtube.com/watch?v=7kphieW4yl4
    at makeError (C:\Users\Ayush\AppData\Roaming\npm\node_modules\udacimak\node_modules\execa\lib\error.js:56:11)
    at handlePromise (C:\Users\Ayush\AppData\Roaming\npm\node_modules\udacimak\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Abdullah-AlEyoni** [comment]
whats output when u run 
`npm -v` , `node -v` , `udacimak -v`  and `npm install -g udacimak`

**Comment by ayushbathrey** [comment]
npm version: 6.13.4
node version: v12.15.0
udacimak version: v1.4.5
On executing "npm install -g udacimak", it downloads and installs the package

**Comment by Abdullah-AlEyoni** [comment]
try to 
`npm cache clean --force` and `rm -rf node_modules `

one Question:- 
when the error appears after witch command?

**Comment by ayushbathrey** [comment]
Error comes after render conmand is executed.

**Comment by Abdullah-AlEyoni** [comment]
try 
`npm -g uninstall udacimak --save`
and 
then follow the  [Install & Update](https://github.com/udacimak/udacimak/wiki/Install-&-Update) Wiki

**Comment by udacimak** [comment]
@ayushbathrey Can you try installing Node JS with `nvm` then install Udacimak, see if that resolve the issue?

**Comment by ayushbathrey** [comment]
It's working fine now.

**Comment by Abhishekdm** [comment]
> It's working fine now.

Hey even I'm facing the same problem. How did you fix?

**Comment by ofarukcaki** [comment]
@ayushbathrey How did you fix?

**Comment by ayushbathrey** [comment]
![image](https://user-images.githubusercontent.com/36703927/77625234-39314180-6f69-11ea-8124-61657d0f9c98.png)

**Comment by ayushbathrey** [comment]
It is working properly and here is the version of node, npm , udacimak that I am currently installed.
![image](https://user-images.githubusercontent.com/36703927/77625490-b066d580-6f69-11ea-86ad-6713e58d55ca.png)

**Comment by ayushbathrey** [comment]
> > It's working fine now.
> 
> Hey even I'm facing the same problem. How did you fix?

All I did was re-installed node.
