### ISSUE TITLE
install error: miniconda / Windows 10

### ISSUE THREAD

**Issue by jess-s** [udacimak/udacimak#80]
**Describe the bug**

Appears to install, then produces the following error:

udacimak : The term 'udacimak' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ udacimak -v
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (udacimak:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**To Reproduce**
1. npm install -g udacimak
2. udacimak -v

Here is what is displayed after install:

npm install -g udacimak
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
C:\Users\jstahl5\AppData\Roaming\npm\udacimak -> C:\Users\jstahl5\AppData\Roaming\npm\node_modules\udacimak\lib\index.js
+ udacimak@1.4.5
updated 1 package in 18.481s

**Expected behavior**
List correct version of udacimak installed

**Comment by udacimak** [comment]
I'm not sure if it'll work with Miniconda, could you try installing directly on your computer?
