### ISSUE TITLE
'udacimak' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by aiolar** [udacimak/udacimak#83]
Hello can you please kindly assist. anytime i type udacimak i get that error message. I know usually when this happens i am supposed to add it to my path but i do not know exactly what to do. Thanks

**Comment by udacimak** [comment]
Have you tried using `nvm` to install Node JS and install Udacimak?

**Comment by aiolar** [comment]
i am running a windows OS. i had to use my powershell to get chocolatey, since it is the package mananager that can allow me download nvm. when i ran NVM to install node, it did install the 64 bit version. Then i ran nvm install udacimak and then it told me that udacimak was 32 bit. now i do not know what next to do

**Comment by aiolar** [comment]
![Screenshot (33)](https://user-images.githubusercontent.com/31485967/77714311-032ba600-6fd9-11ea-8f0a-18a07ac53c2f.png)

**Comment by udacimak** [comment]
@aiolar please read nvm documentation on how to use nvm. `nvm install udacimak` is not a valid command - nvm is not able to directly install npm packages. You'll need to install Node JS first then use `npm` to install Udacimak
