### ISSUE TITLE
Path Error

### ISSUE THREAD

**Issue by pratikwatwani** [udacimak/udacimak#89]
Seems like I have the issue of path to download Udacity Course:

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/16489964/77698062-59bbc480-6f86-11ea-9d66-bcd233e93f0d.png">

An old issue similar to mine was closed, [ERROR:Path to downloaded Udacity course/Nanodegree doesn't exist.](https://github.com/udacimak/udacimak/issues/50)

I'm using Mac OS.

Can someone suggest or help me understand the issue?

**Comment by udacimak** [comment]
Please detail all the steps and commands that you have used so I can have a look

**Comment by pratikwatwani** [comment]
Hi, I got it solved! Thank you!
