### ISSUE TITLE
Render: exit code 3221225781

### ISSUE THREAD

**Issue by aNerdgirl** [udacimak/udacimak#94]
After running the render command, I get the following error:
exit code 3221225781

npm -v
6.13.4
node -v
v12.15.0
udacimak -v
v1.5.0

Updated the youtube-dll.exe as well.
Still the same error.

Already tried to reinstall, as well as everything suggested here:
https://github.com/udacimak/udacimak/issues/78

It worked with a different course, but not with Introduction to Machine Learning with TensorFlow.
I created the JSON files on my laptop and run the rendering on my workstation, not sure if that is relevant. Didn't change the structure at all.

Thanks for the help!

**Comment by udacimak** [comment]
Could you email all the JSON data of the _Introduction to Machine Learning with TensorFlow_ course to udacimak@tutanota.com?

**Comment by aNerdgirl** [comment]
Sorry for causing any trouble, I solved it myself. I was missing some dependencies for the youtube-dll to work.
Thanks!
