### ISSUE TITLE
ERROR: read ECONNRESET

### ISSUE THREAD

**Issue by EmreBayat** [udacimak/udacimak#99]
**Describe the bug**

![image](https://user-images.githubusercontent.com/7987021/77992345-8e38d300-732e-11ea-8289-94862e2377b0.png)

udacimak error log. 

------------------------------------------------------------------------------------------------
2020-03-31T05:52:45.517Z [[31merror[39m]: ERROR: read ECONNRESET
CODE: ECONNRESET
STACK: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
------------------------------------------------------------------------------------------------

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
~$ node --version
v10.15.1
$ npm --version
6.4.1
~$ udacimak --version
v1.5.0

 - Browser [ chrome]

**Course Information**
nd027 version 2.0.0 (locale: en-us): Data Engineering Nanodegree

**Comment by GhaziXX** [comment]
You just need to retype the command and re-render at the same location, it will skip all the downloaded files and complete the rest! That worked for me

**Comment by udacimak** [comment]
@EmreBayat Please send all your JSON data files to udacimak@tutanota.com so I can check if it works on my machine.

**Comment by EmreBayat** [comment]
i will fix it with this. 

https://github.community/t5/Programming-Help-and-Discussion/TLSWrap-onStreamRead-internal-stream-base-commons-js-111-27/td-p/23882

**Comment by EmreBayat** [comment]
is there any method learning nanodegree version which didnt enrolled. 
udacimak listnd only shows currently enrolled nanodegree id and version.

**Comment by udacimak** [comment]
@EmreBayat You can only download the Nanodegrees that you have access to.
